from BaseClasses import ItemClassification
from worlds.smw.Names.ItemName import progressive_powerup


class ItemData:
    def __init__(self, item_id, classification, groups):
        self.groups = groups
        self.classification = classification
        self.id = None if item_id is None else item_id + 172000000

item_table = {
    # These might be better suited towards Regions and locations rather than items, since in logic groups of these unlock the next Chapter/goal sections
    "Squeegee Clean": ItemData("C1G101", ItemClassification.progression, ["missions"]),
    "Befriend Kris (Rel 30)": ItemData("C1G102", ItemClassification.progression, ["missions"]),
    "Give Kris Squeegee 'n Bucket": ItemData("C1G103", ItemClassification.progression, ["missions"]),
    "Take a Shower": ItemData("C1G201", ItemClassification.progression, ["missions"]),
    "Take a Nap": ItemData("C1G202", ItemClassification.progression, ["missions"]),
    "Eat Something (Vending Machine)": ItemData("C1G203", ItemClassification.progression, ["missions"]),
    "Move Bed to the Suite": ItemData("C1G301", ItemClassification.progression, ["missions"]),
    "Repair the Television": ItemData("C1G302", ItemClassification.progression, ["missions"]),
    "Repair Two Fountains": ItemData("C1G303", ItemClassification.progression, ["missions"]),
    "Law Office Workbench Mech Skill": ItemData("C1G401", ItemClassification.progression, ["missions"]),
    "Pick Lily's Lock": ItemData("C1G402", ItemClassification.progression, ["missions"]),
    "Law Office Key": ItemData("C1G403", ItemClassification.progression, ["missions"]),
    "Befriend Det. Dan (Rel 30)": ItemData("C1G501", ItemClassification.progression, ["missions"]),
    "Play Hoopz": ItemData("C1G601", ItemClassification.progression, ["missions"]),
    "Rent money (150)": ItemData("C1G602", ItemClassification.progression, ["missions"]),
    "Buy a House": ItemData("C1G603", ItemClassification.progression, ["missions"]),
    "Befriend Maximillian Moore (Rel 30)": ItemData("C2G101", ItemClassification.progression, ["missions"]),
    "Artemisia Plant": ItemData("C2G102", ItemClassification.progression, ["missions"]),
    "Doctoral Thesis": ItemData("C2G103", ItemClassification.progression, ["missions"]),
    "Befriend Cannonball Coleman (30)": ItemData("C2G201", ItemClassification.progression, ["missions"]),
    "Saxophone Reed": ItemData("C2G202", ItemClassification.progression, ["missions"]),
    "Creativity 1": ItemData("C2G203", ItemClassification.progression, ["missions"]),
    "Coleman's Song": ItemData("C2G204", ItemClassification.progression, ["missions"]),
    "Dusty's $500": ItemData("C2G301", ItemClassification.progression, ["missions"]),
    "Talk to Ewan": ItemData("C2G302", ItemClassification.progression, ["missions"]),
    "Ewan's 3 day lunch": ItemData("C2G303", ItemClassification.progression, ["missions"]),
    "Auction": ItemData("C2G401", ItemClassification.progression, ["missions"]),
    "Shrunken Head": ItemData("C2G402", ItemClassification.progression, ["missions"]),
    "Give Berkeley Shrunken Head": ItemData("C2G401", ItemClassification.progression, ["missions"]),
    "Impress Crystal": ItemData("C2G501", ItemClassification.progression, ["missions"]),
    "Slice of Pizza": ItemData("C2G502", ItemClassification.progression, ["missions"]),
    "Rhythm Game": ItemData("C2G503", ItemClassification.progression, ["missions"]),
    "Thrift Emporium": ItemData("C2G504", ItemClassification.progression, ["missions"]),
    "Crystal's Gift": ItemData("C2G505", ItemClassification.progression, ["missions"]),
    "Three Friends (50 Rel)": ItemData("C2G601", ItemClassification.progression, ["missions"]),
    "Gramma Hattie's $500": ItemData("C2G602", ItemClassification.progression, ["missions"]),
    "Two Promotions (Hoopz, Doc, Comic, Motocross)": ItemData("C2G603", ItemClassification.progression, ["missions"]),
    "Moogoo Monkey": ItemData("C3G101", ItemClassification.progression, ["missions"]),
    "Bulletin Board": ItemData("C3G102", ItemClassification.progression, ["missions"]),
    "Mysterious Briefcase": ItemData("C3G103", ItemClassification.progression, ["missions"]),
    "Rigged Briefcase": ItemData("C3G104", ItemClassification.progression, ["missions"]),
    "Creativity 5": ItemData("C3G201", ItemClassification.progression, ["missions"]),
    "Ewan's Factory Fix": ItemData("C3G202", ItemClassification.progression, ["missions"]),
    "Challenge Dusty Hogg(6-7pm)": ItemData("C3G203",ItemClassification.progression, ["missions"]),
    "Polly's Factory Help(50 Rel)": ItemData("C3G204", ItemClassification.progression, ["missions"]),
    "Body 5 or Charisma 5": ItemData("C3G301", ItemClassification.progression, ["missions"]),
    "Cemetery(11pm)": ItemData("C3G302", ItemClassification.progression, ["missions"]),
    "Cemetery Guard": ItemData("C3G303", ItemClassification.progression, ["missions"]),
    "Group Rep (2 req)": ItemData("C3G401", ItemClassification.progression, ["missions"]),
    "Club Zydeco Tickets(2am)": ItemData("C3G402", ItemClassification.progression, ["missions"]),
    "Curator": ItemData("C3G501", ItemClassification.progression, ["missions"]),
    # museum exhibits might be progressive, I don't remember if you can buy em separately or in order
    "Museum Exhibit Purchase": ItemData("C3G502", ItemClassification.progression, ["missions"]),
    "Roxy's Travel Expenses (300)": ItemData("C3G503", ItemClassification.progression, ["missions"]),
    "Sailor's Coat": ItemData("C3G601", ItemClassification.progression, ["missions"]),
    "Fake Beard": ItemData("C3G602", ItemClassification.progression, ["missions"]),
    "Sailor's Cap": ItemData("C3G603", ItemClassification.progression, ["missions"]),
    "Costume from Mambo Loa": ItemData("C3G604", ItemClassification.progression, ["missions"]),
    "Talk to Olde Salty": ItemData("C3G605", ItemClassification.progression, ["missions"]),
    "Prove You Aren't a Vampire": ItemData("C4G101", ItemClassification.progression, ["missions"]),
    "Dark Tree": ItemData("C4G102", ItemClassification.progression, ["missions"]),
    "Find a Light": ItemData("C4G103", ItemClassification.progression, ["missions"]),
    "Capture the Albino Alligator": ItemData("C4G104", ItemClassification.progression, ["missions"]),
    "Hickory Stump Meetup(Midnight)": ItemData("C4G201", ItemClassification.progression, ["missions"]),
    "Fiddle the Red Man": ItemData("C4G202", ItemClassification.progression, ["missions"]),
    "Convince Clem to Show You Out": ItemData("C4G301", ItemClassification.progression, ["missions"]),
    "Meet Boo at the Mausoleum Entrance": ItemData("C4G302", ItemClassification.progression, ["missions"]),
    "Mausoleum Traversal": ItemData("C4G303", ItemClassification.progression, ["missions"]),
    "Find Someone to Write a Letter": ItemData("C4G401", ItemClassification.progression, ["missions"]),
    "Paradise Island Messenger": ItemData("C4G402", ItemClassification.progression, ["missions"]),
    "Popularity 40": ItemData("C4G403", ItemClassification.progression, ["missions"]),
    "Paradise Island Map": ItemData("C4G404", ItemClassification.progression, ["missions"]),
    "Bring Map to Gordie": ItemData("C4G405", ItemClassification.progression, ["missions"]),
    "Dancing Nutria": ItemData("C4G501", ItemClassification.progression, ["missions"]),
    "Give Nutria to Roxie": ItemData("C4G502", ItemClassification.progression, ["missions"]),
    "Roxie's $5000": ItemData("C4G503", ItemClassification.progression, ["missions"]),
    "Tightrope Walker": ItemData("C4G504", ItemClassification.progression, ["missions"]),
    "Find Misty a Date": ItemData("C4G505", ItemClassification.progression, ["missions"]),
    "Popularity 50": ItemData("C4G601", ItemClassification.progression, ["missions"]),
    "Dusty Hogg Performance (Rel 50)": ItemData("C4G602", ItemClassification.progression, ["missions"]),
    "Sue Pirnova Performance (Rel 50)": ItemData("C4G603", ItemClassification.progression, ["missions"]),
    "Stage Decorations": ItemData("C4G604", ItemClassification.progression, ["missions"]),
    "Attend the Play": ItemData("C4G605", ItemClassification.progression, ["missions"]),
    "Travel to Paradise Island": ItemData("C5G101", ItemClassification.progression, ["missions"]),
    "Trivia Contest": ItemData("C5G102", ItemClassification.progression, ["missions"]),
    "Insult Contestants": ItemData("C5G103", ItemClassification.progression, ["missions"]),
    "Convince Polly (Rel 70)": ItemData("C5G201", ItemClassification.progression, ["missions"]),
    "Secret Lab": ItemData("C5G202", ItemClassification.progression, ["missions"]),
    "Find the Correct Document (Logic 6)": ItemData("C5G203", ItemClassification.progression, ["missions"]),
    "Blueprints for Luthor": ItemData("C5G204", ItemClassification.progression, ["missions"]),
    "Find Bayou Boo": ItemData("C5G301", ItemClassification.progression, ["missions"]),
    "Free Bayou Boo (Mech 7)": ItemData("C5G302", ItemClassification.progression, ["missions"]),
    "Cure for Vampirism": ItemData("C5G303", ItemClassification.progression, ["missions"]),
    "Chocolate for Boo": ItemData("C5G304", ItemClassification.progression, ["missions"]),
    "Befriend Harlan (Rel 30)": ItemData("C5G401", ItemClassification.progression, ["missions"]),
    "Escape": ItemData("C5G402", ItemClassification.progression, ["missions"]),
    "Premiere Ticket": ItemData("C5G501", ItemClassification.progression, ["missions"]),
    "Impress Lily (Rep & Rel 70)": ItemData("C5G502", ItemClassification.progression, ["missions"]),
    "All Black Dress code": ItemData("C5G503", ItemClassification.progression, ["missions"]),
    "Attend Premiere": ItemData("C5G504", ItemClassification.progression, ["missions"]),
    "Find an Inventor": ItemData("C5G601", ItemClassification.progression, ["missions"]),
    "Sue's 10 Nuclear Fuel Rods": ItemData("C5G602", ItemClassification.progression, ["missions"]),
    "Find a Contractor": ItemData("C5G603", ItemClassification.progression, ["missions"]),
    "Find the Correct Date": ItemData("C5G604", ItemClassification.progression, ["missions"]),
    "Time Machine": ItemData("C5G605", ItemClassification.progression, ["missions"]),

}